{
  description = "trizzy 71 nix config";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05"; # pull packages from stable branch `nixos-26.05`
    home-manager = {
      url = "github:nix-community/home-manager/release-26.05"; # version matches 26.05
      inputs.nixpkgs.follows = "nixpkgs"; # use same packages as system to save storage and prevents version conflicts
    };
  };

  outputs =
    { nixpkgs, home-manager, ... }:
    {

      # Mac - home-manager
      homeConfigurations."macbook" = home-manager.lib.homeManagerConfiguration {
        pkgs = import nixpkgs {
          system = "aarch64-darwin";
          config.allowUnfree = true;
        };
        modules = [
          ./hosts/macbook/home.nix
        ];
      };

      # Deprecated Arch - standalone home-manager on Linux
      # homeConfigurations."arch" = home-manager.lib.homeManagerConfiguration {
      #   pkgs = import nixpkgs {
      #     system = "x86_64-linux";
      #     config.allowUnfree = true;
      #   };
      #   modules = [
      #     ./hosts/arch/home.nix
      #   ];
      # };

      # Dell - NixOS
      nixosConfigurations."dell" = nixpkgs.lib.nixosSystem {
        # declares target config
        system = "x86_64-linux"; # architecture
        modules = [
          # building blocks for the system
          ./hosts/dell/configuration.nix # main config file
          /etc/nixos/hardware-configuration.nix # generated by the hardware on install. requires `--impure` on rebuild
          ./modules/base-system.nix # core settings - systemd, zsh, nix
          ./modules/user-tristan.nix # user account
          ./modules/exit-node.nix # ssh and tailscale
          home-manager.nixosModules.home-manager # building blocks for personal environment - hosts/dell/home.nix
          {
            home-manager.useGlobalPkgs = true; # use the same packages as system
            home-manager.useUserPackages = true;
            home-manager.users.tristan = import ./hosts/dell/home.nix; # configure hm to use `tristan` user
          }
        ];
      };

      # frank-test - NixOS
      nixosConfigurations."frank-test" = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./hosts/frank-test/configuration.nix
          ./hosts/frank-test/hardware-configuration.nix
          ./modules/base-system.nix
          ./modules/user-tristan.nix
          ./modules/exit-node.nix
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.tristan = import ./hosts/frank-test/home.nix;
          }
        ];
      };

      # sdi-test - NixOS
      nixosConfigurations."2-test" = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./hosts/2-test/configuration.nix
          ./hosts/2-test/hardware-configuration.nix
          ./modules/base-system.nix
          ./modules/user-tristan.nix
          ./modules/exit-node.nix
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.tristan = import ./hosts/2-test/home.nix;
          }
        ];
      };

      # tristan — NixOS gaming desktop (Nvidia)
      nixosConfigurations."tristan" = nixpkgs.lib.nixosSystem {
        # declares target config
        system = "x86_64-linux"; # architecture
        modules = [
          # building blocks for system
          ./hosts/tristan/configuration.nix # main config file - hostname, system state, filesystem
          ./hosts/tristan/hardware-configuration.nix # generated by the hardware on install
          ./modules/base-system.nix # core settings - systemd, zsh, nix
          ./modules/user-tristan.nix # user account
          ./modules/ssh-system.nix # ssh - public key
          ./modules/desktop-plasma.nix # plasma, pipewire, bluetooth, fonts
          ./modules/desktop-suite.nix # desktop applications, libreoffice, utilities
          ./modules/flatpak.nix # enables flatpaks if you are too lazy to edit config files
          ./modules/gpu-nvidia.nix # nvidia settings, open kernel, power management
          ./modules/gaming.nix # launchers, power/thermal diag, gamemode/gamescope
          home-manager.nixosModules.home-manager # building blocks for personal environment - hosts/tristan/home.nix
          {
            home-manager.useGlobalPkgs = true; # use the same packages as system
            home-manager.useUserPackages = true;
            home-manager.backupFileExtension = "hm-bak"; # rename existing dotfiles instead of aborting
            home-manager.users.tristan = import ./hosts/tristan/home.nix; # configure to use `tristan` user
          }
        ];
      };

      # taryn — NixOS gaming desktop (AMD)
      nixosConfigurations."taryn" = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./hosts/taryn/configuration.nix
          ./hosts/taryn/hardware-configuration.nix
          ./modules/base-system.nix
          ./modules/user-taryn.nix
          ./modules/desktop-plasma.nix
          ./modules/desktop-suite.nix
          ./modules/flatpak.nix
          ./modules/gpu-amd.nix
          ./modules/gaming.nix
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.backupFileExtension = "hm-bak";
            home-manager.users.taryn = import ./hosts/taryn/home.nix;
          }
        ];
      };
    };
}
